# Defaults which will be overwritten
#
---
settings:
  blah: moo
  foo: blah
  log_file: false
  
thetvdb:
  api_key: 31384A8E0F418F3B
  mirror: http://thetvdb.com # should be changed to use the api prefered method of finding the correct mirror
  default: true # always query thetvdb
