# Defaults which will be overwritten
#
# cp to config.yaml with sections that you wish to change
#
---
settings:
  blah: moo
  foo: blah
  log_file: false
  
thetvdb:
  api_key: 31384A8E0F418F3B
  mirror: http://thetvdb.com # should be changed to use the api prefered method of finding the correct mirror
  default: true              # not used

missing:
  start_at_first_found: false # enable when you want to start at the first found episode of a season and not 01
  
sonarr:
  enable: false
  api_key: ABC
  api_url: http://localhost:8989/api